version: '3'

services:
  redis-db:
    image: redis:latest
    container_name: redis-db
    restart: always
    ports:
      - '6379:6379'
    env_file:
      - docker.env
    networks:
      - marketplace-backend

  postgres-db:
    image: postgres
    container_name: postgres-db
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - docker.env
    networks:
      - marketplace-backend

networks:
  marketplace-backend:
    driver: bridge